db.url=jdbc:sqlserver://localhost:1433;databaseName=TrainTicketing_DBASE;encrypt=true;trustServerCertificate=true
db.user=sa
db.password=admin123

mail.host=smtp.gmail.com
mail.port=587
mail.username=ticketappsiemens@gmail.com
mail.password=gbet qmuj zrph yaoc